// react/contact-form/src/App.js
import React, { useState } from 'react';
import './App.css';

function App() {
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    message: ''
  });

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prevState => ({
      ...prevState,
      [name]: value
    }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    try {
      const response = await fetch('http://localhost:3001/submit', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(formData)
      });

      const data = await response.json();
      console.log('Success:', data);
      // Optionally, you can reset the form after successful submission
      setFormData({ name: '', email: '', message: '' });
    } catch (error) {
      console.error('Error:', error);
    }
  };

  return (
    <div className="App">
      <h1>Contact Us</h1>
      <form onSubmit={handleSubmit}>
        <label htmlFor="name">Name:</label>
        <input type="text" id="name" name="name" value={formData.name} onChange={handleChange} required /><br /><br />

        <label htmlFor="email">Email:</label>
        <input type="email" id="email" name="email" value={formData.email} onChange={handleChange} required /><br /><br />

        <label htmlFor="message">Message:</label><br />
        <textarea id="message" name="message" rows="4" value={formData.message} onChange={handleChange} required></textarea><br /><br />

        <button type="submit">Submit</button>
      </form>
    </div>
  );
}

export default App;

// svelete/svelte-contact-form/src/App.svelte
<script>
	let name = '';
	let email = '';
	let message = '';
  
	const handleSubmit = async () => {
	  const formData = { name, email, message };
  
	  try {
		const response = await fetch('http://localhost:3001/submit', {
		  method: 'POST',
		  headers: {
			'Content-Type': 'application/json'
		  },
		  body: JSON.stringify(formData)
		});
  
		const data = await response.json();
		console.log('Success:', data);
		// Optionally, you can reset the form after successful submission
		name = '';
		email = '';
		message = '';
	  } catch (error) {
		console.error('Error:', error);
	  }
	};
  </script>
  
  <style>
	/* Add your styles here */
  </style>
  
  <h1>Contact Us</h1>
  
  <form on:submit|preventDefault={handleSubmit}>
	<label for="name">Name:</label>
	<input type="text" id="name" bind:value={name} required><br><br>
  
	<label for="email">Email:</label>
	<input type="email" id="email" bind:value={email} required><br><br>
  
	<label for="message">Message:</label><br>
	<textarea id="message" bind:value={message} required></textarea><br><br>
  
	<button type="submit">Submit</button>
  </form>
